run:
  modules-download-mode: vendor
  timeout: 5m

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    # Ignore magic numbers in klog.V() calls until we clean them up.
    - linters:
        - gomnd
      source: "klog.V\\("
    # Ignore long generate commands.
    - linters:
        - lll
      source: "^\\/\\/go:generate"
    # Ignore missing non-pointer fields in v1meta options structs.
    - linters:
        - exhaustivestruct
      source: "v1meta\\.(List|Get|Delete)Options"

# List for enabled linters can be generated for updates using the following command.
# golangci-lint linters | grep -E '^\S+:' | cut -d: -f1 | sort | sed 's/^/    - /g' | grep -v -E "($(grep '^  disable:' -A 100 .golangci.yml  | grep -E '    - \S+$' | awk '{print $2}' | tr \\n '|' | sed 's/|$//g'))"
linters:
  disable-all: false
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exhaustivestruct
    - exportloopref
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - stylecheck
    - testpackage
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - wrapcheck
    - wsl
  disable:
    - gci
    - gochecknoglobals
    - godox
    - goerr113
